apiVersion: apps/v1
kind: Deployment
metadata:
  name: voicelingo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voicelingo
  template:
    metadata:
      labels:
        app: voicelingo
    spec:
      containers:
      - name: voicelingo
        image: avigyan2212/devsecops-voicelingo:latest
        imagePullPolicy: Always
        command: ["flask","run","--host=0.0.0.0","--port=5000"]
        ports:
        - containerPort: 5000
