apiVersion: v1
kind: Service
metadata:
  name: voicelingo-service
spec:
  type: ClusterIP
  selector:
    app: voicelingo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32645
